apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesage-agent.fullname" . }}
  labels:
    {{- include "kubesage-agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: health
  selector:
    {{- include "kubesage-agent.selectorLabels" . | nindent 4 }}
